name: test

on: push

jobs:

  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: timedatectl
  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: echo date /t 
  job3:
    name: job3
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: date 
  job4:
    name: job4
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: timedatectl

